# Generated by Django 6.0.2 on 2026-04-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='ai_decision_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='fraud_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
