from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# ── Policy ──────────────────────────────────────────────────────────────────

class Policy(models.Model):
    """
    An insurance policy created by an insurer and optionally assigned to a user.
    weather_threshold_* fields define when auto-claims are triggered.
    """
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    insurer = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='created_policies'
    )
    # Users covered by this policy
    beneficiaries = models.ManyToManyField(
        User, blank=True, related_name='policies'
    )
    # Payout rules
    max_payout_per_claim = models.DecimalField(max_digits=10, decimal_places=2, default=1200)
    payout_percentage = models.DecimalField(max_digits=5, decimal_places=2, default=80.00)
    max_claims_per_month = models.IntegerField(default=5)
    monthly_premium = models.DecimalField(max_digits=8, decimal_places=2, default=129.00)

    # ── Weather thresholds for auto-claim ─────────────────────────────────
    # A claim is auto-triggered when ANY of these thresholds are exceeded.
    rainfall_threshold_mm = models.FloatField(
        default=5.0,
        help_text="Rainfall in mm above which auto-claim triggers"
    )
    wind_speed_threshold_kph = models.FloatField(
        default=50.0,
        help_text="Wind speed in km/h above which auto-claim triggers"
    )
    temperature_min_threshold_c = models.FloatField(
        default=5.0,
        help_text="Minimum temperature (°C) below which auto-claim triggers"
    )
    temperature_max_threshold_c = models.FloatField(
        default=45.0,
        help_text="Maximum temperature (°C) above which auto-claim triggers"
    )
    # ML-ready field: predicted claim probability threshold (0.0 - 1.0)
    ml_claim_probability_threshold = models.FloatField(
        default=0.65,
        help_text="ML model score above which auto-claim triggers"
    )

    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "policies"
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.name} (by {self.insurer.email})"


# ── WeatherLog ───────────────────────────────────────────────────────────────

class WeatherLog(models.Model):
    """
    Stores weather observations used as evidence for claims.
    Fetched by the background monitor task.
    """
    city = models.CharField(max_length=100)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)

    temperature_c = models.FloatField()
    feels_like_c = models.FloatField(null=True, blank=True)
    humidity_pct = models.FloatField(null=True, blank=True)
    rainfall_mm = models.FloatField(default=0.0)
    wind_speed_kph = models.FloatField(default=0.0)
    condition_text = models.CharField(max_length=200)
    condition_code = models.IntegerField(default=1000)

    # Risk score (set by ML model)
    ml_risk_score = models.FloatField(
        null=True, blank=True,
        help_text="ML model predicted claim probability (0.0 - 1.0)"
    )
    is_disruption = models.BooleanField(default=False)

    recorded_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-recorded_at']

    def __str__(self):
        return f"{self.city} @ {self.recorded_at:%Y-%m-%d %H:%M} — {self.condition_text}"


# ── Claim ────────────────────────────────────────────────────────────────────

class Claim(models.Model):
    """
    An insurance claim — either manually filed or auto-generated by the weather monitor.
    """
    SOURCE_MANUAL = 'manual'
    SOURCE_AUTO   = 'auto'
    SOURCE_CHOICES = [
        (SOURCE_MANUAL, 'Manual'),
        (SOURCE_AUTO,   'Auto-Generated'),
    ]

    STATUS_PENDING  = 'pending'
    STATUS_APPROVED = 'approved'
    STATUS_REJECTED = 'rejected'
    STATUS_CHOICES = [
        (STATUS_PENDING,  'Pending'),
        (STATUS_APPROVED, 'Approved'),
        (STATUS_REJECTED, 'Rejected'),
    ]

    DISRUPTION_TYPES = [
        ('heavy_rain',       'Heavy Rain'),
        ('flood',            'Flood'),
        ('storm',            'Storm / Thunderstorm'),
        ('extreme_heat',     'Extreme Heat'),
        ('extreme_cold',     'Extreme Cold'),
        ('shutdown',         'Shutdown'),
        ('platform_outage',  'Platform Outage'),
        ('traffic_blockage', 'Traffic Blockage'),
        ('other',            'Other'),
    ]

    # Who filed / is affected
    claimant = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='claims'
    )
    policy = models.ForeignKey(
        Policy, on_delete=models.SET_NULL, null=True, blank=True, related_name='claims'
    )

    # Claim metadata
    claim_id = models.CharField(max_length=30, unique=True)  # e.g. GS-2026-483920
    source = models.CharField(max_length=10, choices=SOURCE_CHOICES, default=SOURCE_MANUAL)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default=STATUS_PENDING)
    disruption_type = models.CharField(max_length=30, choices=DISRUPTION_TYPES, default='heavy_rain')

    # Location & timing
    city = models.CharField(max_length=100, default='Vadodara')
    platform = models.CharField(max_length=100, blank=True)
    incident_date = models.DateField()
    incident_time = models.TimeField(null=True, blank=True)

    # Earnings
    expected_earnings = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    actual_earnings   = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    estimated_loss    = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    payout_amount     = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    # Insurer review
    reviewed_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True, related_name='reviewed_claims'
    )
    review_note = models.TextField(blank=True)
    reviewed_at = models.DateTimeField(null=True, blank=True)

    # AI verification
    ai_confidence     = models.FloatField(null=True, blank=True)
    ai_reasoning      = models.TextField(blank=True)
    ai_approved       = models.BooleanField(null=True, blank=True)

    # Linked weather evidence
    weather_log = models.ForeignKey(
        WeatherLog, on_delete=models.SET_NULL, null=True, blank=True, related_name='claims'
    )

    description = models.TextField(blank=True)
    created_at  = models.DateTimeField(auto_now_add=True)
    updated_at  = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.claim_id} — {self.claimant.email} [{self.status}]"

    def save(self, *args, **kwargs):
        # Auto-calculate loss and payout before saving
        self.estimated_loss = max(0, self.expected_earnings - self.actual_earnings)
        if not self.payout_amount:
            self.payout_amount = round(float(self.estimated_loss) * 0.8, 2)
        super().save(*args, **kwargs)


# ── Notification ─────────────────────────────────────────────────────────────

class Notification(models.Model):
    """
    In-app notifications for users — auto-claim alerts, payout confirmations, etc.
    """
    TYPE_CLAIM_AUTO    = 'claim_auto'
    TYPE_CLAIM_APPROVED = 'claim_approved'
    TYPE_CLAIM_REJECTED = 'claim_rejected'
    TYPE_WEATHER_ALERT  = 'weather_alert'
    TYPE_GENERAL        = 'general'

    TYPE_CHOICES = [
        (TYPE_CLAIM_AUTO,     'Auto-Claim Created'),
        (TYPE_CLAIM_APPROVED, 'Claim Approved'),
        (TYPE_CLAIM_REJECTED, 'Claim Rejected'),
        (TYPE_WEATHER_ALERT,  'Weather Alert'),
        (TYPE_GENERAL,        'General'),
    ]

    recipient   = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notifications')
    notif_type  = models.CharField(max_length=20, choices=TYPE_CHOICES, default=TYPE_GENERAL)
    title       = models.CharField(max_length=200)
    body        = models.TextField()
    claim       = models.ForeignKey(Claim, on_delete=models.SET_NULL, null=True, blank=True)
    is_read     = models.BooleanField(default=False)
    created_at  = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"[{self.notif_type}] {self.title} → {self.recipient.email}"