# Generated by Django 6.0.2 on 2026-04-03 13:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('temperature_c', models.FloatField()),
                ('feels_like_c', models.FloatField(blank=True, null=True)),
                ('humidity_pct', models.FloatField(blank=True, null=True)),
                ('rainfall_mm', models.FloatField(default=0.0)),
                ('wind_speed_kph', models.FloatField(default=0.0)),
                ('condition_text', models.CharField(max_length=200)),
                ('condition_code', models.IntegerField(default=1000)),
                ('ml_risk_score', models.FloatField(blank=True, help_text='ML model predicted claim probability (0.0 - 1.0)', null=True)),
                ('is_disruption', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.CharField(max_length=30, unique=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto-Generated')], default='manual', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('disruption_type', models.CharField(choices=[('heavy_rain', 'Heavy Rain'), ('flood', 'Flood'), ('storm', 'Storm / Thunderstorm'), ('extreme_heat', 'Extreme Heat'), ('extreme_cold', 'Extreme Cold'), ('shutdown', 'Shutdown'), ('platform_outage', 'Platform Outage'), ('traffic_blockage', 'Traffic Blockage'), ('other', 'Other')], default='heavy_rain', max_length=30)),
                ('city', models.CharField(default='Vadodara', max_length=100)),
                ('platform', models.CharField(blank=True, max_length=100)),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField(blank=True, null=True)),
                ('expected_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_loss', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('ai_reasoning', models.TextField(blank=True)),
                ('ai_approved', models.BooleanField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('claim_auto', 'Auto-Claim Created'), ('claim_approved', 'Claim Approved'), ('claim_rejected', 'Claim Rejected'), ('weather_alert', 'Weather Alert'), ('general', 'General')], default='general', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.claim')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('max_payout_per_claim', models.DecimalField(decimal_places=2, default=1200, max_digits=10)),
                ('payout_percentage', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('max_claims_per_month', models.IntegerField(default=5)),
                ('monthly_premium', models.DecimalField(decimal_places=2, default=129.0, max_digits=8)),
                ('rainfall_threshold_mm', models.FloatField(default=5.0, help_text='Rainfall in mm above which auto-claim triggers')),
                ('wind_speed_threshold_kph', models.FloatField(default=50.0, help_text='Wind speed in km/h above which auto-claim triggers')),
                ('temperature_min_threshold_c', models.FloatField(default=5.0, help_text='Minimum temperature (°C) below which auto-claim triggers')),
                ('temperature_max_threshold_c', models.FloatField(default=45.0, help_text='Maximum temperature (°C) above which auto-claim triggers')),
                ('ml_claim_probability_threshold', models.FloatField(default=0.65, help_text='ML model score above which auto-claim triggers')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiaries', models.ManyToManyField(blank=True, related_name='policies', to=settings.AUTH_USER_MODEL)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='core.policy'),
        ),
        migrations.AddField(
            model_name='claim',
            name='weather_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='core.weatherlog'),
        ),
    ]
