# Generated by Django 6.0.2 on 2026-04-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_claim_ai_decision_reason_claim_fraud_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='incident_date',
        ),
    ]
